config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {registrations: 'registrations'}

  get 'welcome/patienthome' => 'welcome#patienthome'
  get 'welcome/providerhome' => 'welcome#providerhome'
  get 'welcome/healthplanhome' => 'welcome#healthplanhome'
  get 'welcome/adminhome' => 'welcome#adminhome'

  resources :providers do
  	collection do
  		get 'search'
  	end
  end

  resources :patients do
  end

  resources :licenses do
  end

  resources :locations do
  end

  resources :appointments do
  end

  resources :licexpirations do
  end

  resources :patientrelations do
  end

  authenticated :user do
  	root 'defineuser#index', as: "authenticated_root"
  end

  root 'welcome#index'		
  
end

app/models/appointment.rb
class Appointment < ActiveRecord::Base

	belongs_to :provider
	belongs_to :patient
	belongs_to :appointmenttype

end

app/models/appointmenttype.rb
class Appointmenttype < ActiveRecord::Base

	has_many :appointments
	accepts_nested_attributes_for :appointments

end

app/models/license.rb
class License < ActiveRecord::Base

	has_many :licexpirations
	has_many :providers, through: :licexpirations

end

app/models/licexpiration.rb
class Licexpiration < ActiveRecord::Base

	belongs_to :provider
	belongs_to :license

	accepts_nested_attributes_for :license
	
end

app/models/location.rb
class Location < ActiveRecord::Base
	belongs_to :provider
end

app/models/patient.rb
class Patient < ActiveRecord::Base

	belongs_to :user

	has_many :patientrelations
	has_many :providers, through: :patientrelations
	has_many :appointments

	has_attached_file :image, styles: { medium: "400x400#", small: "200x200#", thumb: "100x100" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

end

app/models/patientrelation.rb
class Patientrelation < ActiveRecord::Base

	belongs_to :provider
	belongs_to :patient
	belongs_to :patientrelationtype

	accepts_nested_attributes_for :patient
end

app/models/patientrelationtype.rb
class Patientrelationtype < ActiveRecord::Base

	has_many :patientrelations

end

app/models/provider.rb
class Provider < ActiveRecord::Base
	searchkick

	belongs_to :user
	belongs_to :specialty

	has_many :patientrelations
	has_many :patients, through: :patientrelations
	accepts_nested_attributes_for :patientrelations, reject_if: :all_blank, allow_destroy: true
	accepts_nested_attributes_for :patients, reject_if: :all_blank, allow_destroy: true

	has_many :locations
	accepts_nested_attributes_for :locations, reject_if: :all_blank, allow_destroy: true

	has_many :licexpirations
	has_many :licenses, through: :licexpirations
	accepts_nested_attributes_for :licexpirations, reject_if: :all_blank, allow_destroy: true
	accepts_nested_attributes_for :licenses, reject_if: :all_blank, allow_destroy: true

	has_many :appointments

	validates :name, :specialty, :image, presence: true
	has_attached_file :image, styles: { medium: "400x400#", small: "200x200#", thumb: "100x100" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/specialty.rb
class Specialty < ActiveRecord::Base

	has_many :providers

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :usertype

  has_many :providers
  has_many :patients
end

app/models/usertype.rb
class Usertype < ActiveRecord::Base
	has_many :users
end

app/controllers/providers_controller.rb
class ProvidersController < ApplicationController
	before_action :find_provider, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show]
	

  def search
    if params[:search].present?
      @providers = Provider.search(params[:search])
    else
      @providers = Provider.all
    end
  end


	def index
		@provider = Provider.all.order("created_at DESC")
	end

	def show
	end

	def new
		@provider = current_user.providers.build
	end

	def create
		@provider = current_user.providers.build(provider_params)

		if @provider.save
			redirect_to @provider, notice: "Successfully created new provider"
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @provider.update(provider_params)
			redirect_to @provider
		else
			render 'edit'
		end
	end

	def destroy
		@provider.destroy
		redirect_to root_path, notice: "Successfully deleted provider"
	end

	private

		def provider_params
			params.require(:provider). permit(:name, :npi, :user_id, :specialty, :specialty_id, :image, 
				patientrelations_attributes: [:id, :provider_id, :patient_id, :patientrelationtypes_id, :_destroy, patient_attributes: [:id, :first_name, :last_name, :member_id, :_destroy]], 
				locations_attributes: [:id, :street_1, :street_2, :city, :state, :zip, :loc_type, :_destroy], 
				licexpirations_attributes: [:id, :provider_id, :license_id, :expiration_year, :_destroy, license_attributes: [:id, :state, :_destroy]])
		end

		def find_provider
			@provider = Provider.find(params[:id])
		end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/defineuser_helper.rb
module DefineuserHelper
end

app/helpers/licenses_helper.rb
module LicensesHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/providers/_form.html.haml
= simple_form_for @provider, HTML: { multipart: true } do |f|
	- if @provider.errors.any?
		#errors
			%p
				= @provider.errors.count
				Prevented this provider from saving
			%ul
				- @provider.errors.full_messages.each do |msg|
					%li = msg
	.panel-body
		= f.input :name, input_html: {class: 'form-control'}
		= f.input :npi, input_html: {class: 'form-control'}
		= f.input :user_id, input_html: {class: 'form-control'}
		= f.association :specialty, label_method: :specialty, value_method: :id, include_blank: false
		= f.input :image, input_html: {class: 'form-control'}

		.row
			.col-md-12
				%h3 Locations
				#patients
					= f.simple_fields_for :locations do |location|
						= render 'location_fields', f: location
					.links
						= link_to_add_association 'Add Location', f, :locations, class: "btn btn-default add-button"

		.row
			.col-md-12
				%h3 Patients
				#patients
					%fieldset#provider-patients
						%ol
							= f.simple_fields_for :patientrelations do |patientrelation|
								= render 'patientrelation_fields', f: patientrelation
						= link_to_add_association 'Add Patient', f, :patientrelations, class: "btn btn-default add-button", 'data-association-insertion-node' => "#provider-patients ol", 'data-association-insertion-method' => "append", :wrap_object => Proc.new {|patientrelation| patientrelation.build_patient; patientrelation }

		.row
			.col-md-12
				%h3 Licenses
				#patients
					%fieldset#provider-licenses
						%ol
							= f.simple_fields_for :licexpirations do |licexpiration|
								= render 'licexpiration_fields', f: licexpiration
						= link_to_add_association 'add license', f, :licexpirations, class: "btn btn-default add-button", 'data-association-insertion-node' => "#provider-licenses ol", 'data-association-insertion-method' => "append", :wrap_object => Proc.new {|licexpiration| licexpiration.build_license; licexpiration }

	= f.button :submit, class: "btn btn-primary"

app/views/providers/_licexpiration_fields.html.haml
%li.control-group.nested-fields
  .controls
    = f.input :expiration_year, input_html: {class: 'form-control'}
    = f.fields_for :license do |licexpiration_license|
      = licexpiration_license.text_field :state
    = link_to_remove_association "remove", f

app/views/providers/_location_fields.html.haml
.form-inline.clearfix
	.nested-fields
		=f.input :street_1, input_html: {class: "form-input form-control"}
		=f.input :street_2, input_html: {class: "form-input form-control"}
		=f.input :city, input_html: {class: "form-input form-control"}
		=f.input :state, input_html: {class: "form-input form-control"}
		=f.input :zip, input_html: {class: "form-input form-control"}
		= link_to_remove_association "Remove", f, class: "form-button btn btn-default"

app/views/providers/_patientrelation_fields.html.haml
%li.control-group.nested-fields
  .controls
    = f.input :patientrelationtypes_id, input_html: {class: 'form-control'}
    = f.fields_for :patient do |patientrelation_patient|
      = patientrelation_patient.text_field :first_name
      = patientrelation_patient.text_field :last_name
      = patientrelation_patient.text_field :member_id
    = link_to_remove_association "remove", f

app/views/providers/index.html.haml
- @provider.each_slice(3) do |providers|
	.row
		- providers.each do |provider|
			.col-md-4
				.provider	
					.image_wrapper
						=link_to provider do
							= image_tag provider.image.url(:medium)
						%h2= link_to provider.name, provider

app/views/providers/search.html.haml
.row
  - @providers.each do |provider|
    .col-sm-6.col-md-3
      .thumbnail
        = link_to (image_tag provider.image.url(:medium), class: 'image'), provider

app/views/providers/show.html.haml
.main-content
	#provider_top.row
	.row
		.col-md-4
			=image_tag @provider.image.url(:medium), class: "provider_image"
		.col-md-8
			#provider_info
				.row
					%h1= @provider.name
					%p.description= @provider.specialty.specialty
					%br
				.row
					= link_to "Back", root_path, class: "btn btn-default" 
					- if user_signed_in?
						= link_to "Edit", edit_provider_path, class: "btn btn-default" 
						= link_to "Delete", provider_path, method: :delete, data: { confirm: "Are you sure about that mofo?" }, class: "btn btn-default"	
%br

	/ Nav tabs
	%ul.nav.nav-tabs{:role => "tablist"}
		%li.active{:role => "presentation"}
			%a{"aria-controls" => "patients", "data-toggle" => "tab", :href => "#patients", :role => "tab"} Patients
		%li{:role => "presentation"}
			%a{"aria-controls" => "appointments", "data-toggle" => "tab", :href => "#appointments", :role => "tab"} Appointments
		%li{:role => "presentation"}
			%a{"aria-controls" => "locations", "data-toggle" => "tab", :href => "#locations", :role => "tab"} Locations
		%li{:role => "presentation"}
			%a{"aria-controls" => "licenses", "data-toggle" => "tab", :href => "#licenses", :role => "tab"} Licenses
	/ Tab panes
	.tab-content
		#patients.tab-pane.active{:role => "tabpanel"} 
			%table.table.table-hover
				%thead
					%tr
						%th View Patient
						%th First Name
						%th Last Name
						%th{:colspan => "3"}
				%tbody
					- @provider.patients.each do |patient|
						%tr
							%td= link_to patient.member_id, patient
							%td= patient.last_name
							%td= patient.first_name
			= link_to "New Patient", new_patient_path, class: "btn btn-default" 
		#appointments.tab-pane{:role => "tabpanel"} 
			%table.table.table-hover
				%thead
					%tr
						%th Appt ID
						%th Patient Last Name
						%th Patient First Name
						%th Patient First Name
						%th Appt Confirmed
						%th Appt Type
						%th{:colspan => "6"}
				%tbody
					- @provider.appointments.each do |appointment|
						%tr
							%td= link_to appointment.id, appointment
							%td= appointment.patient.last_name
							%td= appointment.patient.last_name
							%td= appointment.patient.first_name
							%td= appointment.apptconfirmed
							%td= appointment.appointmenttype.apptype
			= link_to "New Appointment", new_appointment_path, class: "btn btn-default" 
		#locations.tab-pane{:role => "tabpanel"} 
			%table.table.table-hover
				%thead
					%tr
						%th ID
						%th Address
						%th City
						%th State
						%th{:colspan => "4"}
				%tbody
					- @provider.locations.each do |location|
						%tr
							%td= link_to location.id, location
							%td= location.street_1
							%td= location.city
							%td= location.state
		#licenses.tab-pane{:role => "tabpanel"} 
			%table.table.table-hover
				%thead
					%tr
						%th License ID
						%th State
						%th Expiration
						%th{:colspan => "3"}
				%tbody
					- @provider.licexpirations.each do |lic_expiration|
						%tr
							%td= link_to lic_expiration.id, lic_expiration
							%td= lic_expiration.license.state
							%td= lic_expiration.expiration_year