config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {registrations: 'registrations'}

  get 'welcome/patienthome' => 'welcome#patienthome'
  get 'welcome/providerhome' => 'welcome#providerhome'
  get 'welcome/healthplanhome' => 'welcome#healthplanhome'
  get 'welcome/adminhome' => 'welcome#adminhome'

  resources :providers do
  	collection do
  		get 'search'
  	end
  end

  resources :patients do
  end

  resources :licenses do
  end

  resources :locations do
  end

  resources :appointments do
  end

  resources :licexpirations do
  end

  resources :patientrelations do
  end

  authenticated :user do
  	root 'defineuser#index', as: "authenticated_root"
  end

  root 'welcome#index'		
  
end

app/models/appointment.rb
class Appointment < ActiveRecord::Base

	belongs_to :provider
	belongs_to :patient
	belongs_to :appointmenttype

end

app/models/appointmenttype.rb
class Appointmenttype < ActiveRecord::Base

	has_many :appointments
	accepts_nested_attributes_for :appointments

end

app/models/license.rb
class License < ActiveRecord::Base

	has_many :licexpirations
	has_many :providers, through: :licexpirations

end

app/models/licexpiration.rb
class Licexpiration < ActiveRecord::Base

	belongs_to :provider
	belongs_to :license

	accepts_nested_attributes_for :license
	
end

app/models/location.rb
class Location < ActiveRecord::Base
	belongs_to :provider
end

app/models/patient.rb
class Patient < ActiveRecord::Base

	belongs_to :user

	has_many :patientrelations
	has_many :providers, through: :patientrelations
	has_many :appointments

	has_attached_file :image, styles: { medium: "400x400#", small: "200x200#", thumb: "100x100" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

end

app/models/patientrelation.rb
class Patientrelation < ActiveRecord::Base

	belongs_to :provider
	belongs_to :patient
	belongs_to :patientrelationtype

	accepts_nested_attributes_for :patient
end

app/models/patientrelationtype.rb
class Patientrelationtype < ActiveRecord::Base

	has_many :patientrelations

end

app/models/provider.rb
class Provider < ActiveRecord::Base
	searchkick

	belongs_to :user
	belongs_to :specialty

	has_many :patientrelations
	has_many :patients, through: :patientrelations
	accepts_nested_attributes_for :patientrelations, reject_if: :all_blank, allow_destroy: true
	accepts_nested_attributes_for :patients, reject_if: :all_blank, allow_destroy: true

	has_many :locations
	accepts_nested_attributes_for :locations, reject_if: :all_blank, allow_destroy: true

	has_many :licexpirations
	has_many :licenses, through: :licexpirations
	accepts_nested_attributes_for :licexpirations, reject_if: :all_blank, allow_destroy: true
	accepts_nested_attributes_for :licenses, reject_if: :all_blank, allow_destroy: true

	has_many :appointments

	validates :name, :specialty, :image, presence: true
	has_attached_file :image, styles: { medium: "400x400#", small: "200x200#", thumb: "100x100" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/specialty.rb
class Specialty < ActiveRecord::Base

	has_many :providers

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :usertype

  has_many :providers
  has_many :patients
end

app/models/usertype.rb
class Usertype < ActiveRecord::Base
	has_many :users
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/defineuser_helper.rb
module DefineuserHelper
end

app/helpers/licenses_helper.rb
module LicensesHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/adminhome.html.haml
ADMIN PAGE

app/views/welcome/healthplanhome.html.haml
Plans

app/views/welcome/index.html.haml
#banner
	.banner_content
		%h1 AACESO
		%p Your online guide to everything health...
		%button= link_to "Sign Up", new_user_registration_path

#testimonial
	.wrapper
		%p.quote "AAceso is the greatest thing ever.  It really helped make my process that much easier"
		%p.name - Mike Michaelson

#callouts
	.callout_inner
		.wrapper
			.callout
				%i.fa.fa-user-md
				%h2= link_to 'Providers', "/welcome/providerhome"
				%p Tilde master cleanse Pinterest, mustache bitters literally distillery Vice small batch Godard. Tote bag shabby chic authentic aesthetic quinoa tattooed. Organic sriracha polaroid dreamcatcher, jean shorts bicycle rights banjo skateboard DIY fap brunch fingerstache Tumblr. PBR swag ugh four loko.
			.callout
				%i.fa.fa-users          
				%h2= link_to 'Patients', "/welcome/patienthome"
				%p Gastropub meh church-key Brooklyn, wayfarers keffiyeh letterpress XOXO aesthetic vegan farm-to-table mixtape vinyl hella. Scenester cardigan vegan fingerstache keytar. Flexitarian tote bag normcore church-key freegan jean shorts Helvetica.
			.callout
				%i.fa.fa-hospital-o
				%h2= link_to 'Health Plans', "/welcome/healthplanhome"
				%p Williamsburg Schlitz Carles deep v brunch. Health goth tilde Shoreditch, VHS single-origin coffee pop-up messenger bag Brooklyn Godard four dollar toast squid iPhone pour-over stumptown mixtape. Twee sriracha actually, tattooed Intelligentsia street art Thundercats Marfa wolf chia flannel Kickstarter.
#bottom_cta
	.wrapper
		%h2 What are you waiting for?
		%p Understand how we can help make your access to care that much better
		%button= link_to "Sign Up Now", new_user_registration_path
		%br

%h2 AAceso Tweets
%ul
	- TwitterApi.our_public_tweets.each do |tweet|
		%li= tweet.text

%footer
	%p &copy; AAceso Health 2015

app/views/welcome/patienthome.html.haml
%h1 PATIENT HOMEPAGE
%p Homepage for patient viewing their own existing dashboard

%h3 Patients
%p Listing of providers associated with this user
%table.table.table-hover
	%thead
		%tr
			%th
			%th View Patient
			%th First Name
			%th Last Name
			%th{:colspan => "4"}
	%tbody
		- current_user.patients.each do |patient|
			%tr
				%td= link_to (image_tag patient.image.url(:thumb)), patient
				%td= link_to patient.member_id, patient
				%td= patient.first_name
				%td= patient.last_name

%h3 Appointments
%p Listing of appointments associated with this user
%table.table.table-hover
	%tbody
		- current_user.patients.each do |patient|
			%tr
				%td= link_to patient.member_id, patient
				%td= patient.first_name
				%td= patient.last_name




= link_to "My Providers", '/providers', class: "btn btn-default" 
= link_to "Create Appointment", new_appointment_path, class: "btn btn-default" 
= link_to "My Pharmacy", '/providers', class: "btn btn-default" 

app/views/welcome/providerhome.html.haml
%h1 PROVIDER DASHBOARD
%p Please select the provider you wish to review

%table.table.table-hover
	%thead
		%tr
			%th 
			%th View Provider
			%th Provider Name
			%th Provider Specialty
			%th{:colspan => "3"}
	%tbody
		- current_user.providers.each do |provider|
			%tr
				%td= link_to (image_tag provider.image.url(:thumb)), provider
				%td= link_to provider.npi, provider
				%td= provider.name
				%td= provider.specialty.specialty

= link_to "Add Provider", new_provider_path, class: "btn btn-default" 