config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {registrations: 'registrations'}

  get 'welcome/patienthome' => 'welcome#patienthome'
  get 'welcome/providerhome' => 'welcome#providerhome'
  get 'welcome/healthplanhome' => 'welcome#healthplanhome'
  get 'welcome/adminhome' => 'welcome#adminhome'

  resources :providers do
  	collection do
  		get 'search'
  	end
  end

  resources :patients do
  end

  resources :licenses do
  end

  resources :locations do
  end

  resources :appointments do
  end

  resources :licexpirations do
  end

  resources :patientrelations do
  end

  authenticated :user do
  	root 'defineuser#index', as: "authenticated_root"
  end

  root 'welcome#index'		
  
end

app/models/appointment.rb
class Appointment < ActiveRecord::Base

	belongs_to :provider
	belongs_to :patient
	belongs_to :appointmenttype

end

app/models/appointmenttype.rb
class Appointmenttype < ActiveRecord::Base

	has_many :appointments
	accepts_nested_attributes_for :appointments

end

app/models/license.rb
class License < ActiveRecord::Base

	has_many :licexpirations
	has_many :providers, through: :licexpirations

end

app/models/licexpiration.rb
class Licexpiration < ActiveRecord::Base

	belongs_to :provider
	belongs_to :license

	accepts_nested_attributes_for :license
	
end

app/models/location.rb
class Location < ActiveRecord::Base
	belongs_to :provider
end

app/models/patient.rb
class Patient < ActiveRecord::Base

	belongs_to :user

	has_many :patientrelations
	has_many :providers, through: :patientrelations
	has_many :appointments

	has_attached_file :image, styles: { medium: "400x400#", small: "200x200#", thumb: "100x100" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

end

app/models/patientrelation.rb
class Patientrelation < ActiveRecord::Base

	belongs_to :provider
	belongs_to :patient
	belongs_to :patientrelationtype

	accepts_nested_attributes_for :patient
end

app/models/patientrelationtype.rb
class Patientrelationtype < ActiveRecord::Base

	has_many :patientrelations

end

app/models/provider.rb
class Provider < ActiveRecord::Base
	searchkick

	belongs_to :user
	belongs_to :specialty

	has_many :patientrelations
	has_many :patients, through: :patientrelations
	accepts_nested_attributes_for :patientrelations, reject_if: :all_blank, allow_destroy: true
	accepts_nested_attributes_for :patients, reject_if: :all_blank, allow_destroy: true

	has_many :locations
	accepts_nested_attributes_for :locations, reject_if: :all_blank, allow_destroy: true

	has_many :licexpirations
	has_many :licenses, through: :licexpirations
	accepts_nested_attributes_for :licexpirations, reject_if: :all_blank, allow_destroy: true
	accepts_nested_attributes_for :licenses, reject_if: :all_blank, allow_destroy: true

	has_many :appointments

	validates :name, :specialty, :image, presence: true
	has_attached_file :image, styles: { medium: "400x400#", small: "200x200#", thumb: "100x100" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/specialty.rb
class Specialty < ActiveRecord::Base

	has_many :providers

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :usertype

  has_many :providers
  has_many :patients
end

app/models/usertype.rb
class Usertype < ActiveRecord::Base
	has_many :users
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController

	before_action :find_patient, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show]

	def index
		@patient = Patient.all.order("created_at DESC")
	end

	def show
		@patient = Patient.find(params[:id])
	end

	def new
		@patient = current_user.patients.build
	end

	def create
		@patient = current_user.patients.build(patient_params)

		if @patient.save
			redirect_to @patient, notice: "Successfully created new patient record"
		els
			render 'new'
		end
	end

	def edit
	end

	def update
		if @patient.update(patient_params)
			redirect_to @patient
		else
			render 'edit'
		end
	end

	def destroy
		@patient.destroy
		redirect_to root_path, notice: "Successfully deleted patient"
	end

	private

		def patient_params
			params.require(:patient). permit(:first_name, :last_name, :member_id, :user_id, :image)
		end

		def find_patient
			@patient = Patient.find(params[:id])
		end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/defineuser_helper.rb
module DefineuserHelper
end

app/helpers/licenses_helper.rb
module LicensesHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/patients/_form.html.haml
= simple_form_for @patient do |f|
	= f.input :first_name
	= f.input :last_name
	= f.input :member_id
	= f.input :user_id
	= f.input :image, input_html: {class: 'form-control'}
	= f.button :submit

app/views/patients/edit.html.haml
%h1 Edit Patient

= render 'form'

app/views/patients/index.html.haml
%p#notice= notice
%h1 Listing Packitems
%table
  %thead
    %tr
      %th{:colspan => "3"}
  %tbody
    - @patient.each do |patient|
      %tr
        %td= patient.last_name
        %td= patient.first_name
        %td= link_to 'Show', patient
        %td= link_to 'Edit', edit_patient_path(patient)
        %td= link_to 'Destroy', patient, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Patient', new_patient_path

app/views/patients/new.html.haml
%h1 Create New Patient

= render 'form'

%br/

= link_to "Back", root_path, class: "btn btn-default"

app/views/patients/show.html.haml
.main-content
	#provider_top.row
		.col-md-4
			=image_tag @patient.image.url(:medium), class: "provider_image"
		.col-md-8
			#provider_info
				%h1= @patient.last_name
				%p.description= @patient.first_name
				%p.description= @patient.member_id				

	.row
		.col-md-12
			#patients
				%h2 Appointments
				%ul
					- @patient.appointments.each do |appointment|
						%li= link_to appointment.provider.name, appointment

	.row
		.col-md-12
			#patients
				%h2 Providers
				%ul
					- @patient.patientrelations.each do |patientrelations|
						%li= patientrelations.provider.name


		.col-md-12
			#patients
				%h2 Plans

	.row
		.col-md-12
			= link_to "Back", root_path, class: "btn btn-default" 
			- if user_signed_in?
				= link_to "Edit", edit_patient_path, class: "btn btn-default" 
				= link_to "Delete", patient_path, method: :delete, data: { confirm: "Are you sure about that mofo?" }, class: "btn btn-default"	
				= link_to "Request Appointment", new_appointment_path, class: "btn btn-default" 