config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {registrations: 'registrations'}

  get 'welcome/patienthome' => 'welcome#patienthome'
  get 'welcome/providerhome' => 'welcome#providerhome'
  get 'welcome/healthplanhome' => 'welcome#healthplanhome'
  get 'welcome/adminhome' => 'welcome#adminhome'

  resources :providers do
  	collection do
  		get 'search'
  	end
  end

  resources :patients do
  end

  resources :licenses do
  end

  resources :locations do
  end

  resources :appointments do
  end

  resources :licexpirations do
  end

  resources :patientrelations do
  end

  authenticated :user do
  	root 'defineuser#index', as: "authenticated_root"
  end

  root 'welcome#index'		
  
end

app/models/appointment.rb
class Appointment < ActiveRecord::Base

	belongs_to :provider
	belongs_to :patient
	belongs_to :appointmenttype

end

app/models/appointmenttype.rb
class Appointmenttype < ActiveRecord::Base

	has_many :appointments
	accepts_nested_attributes_for :appointments

end

app/models/license.rb
class License < ActiveRecord::Base

	has_many :licexpirations
	has_many :providers, through: :licexpirations

end

app/models/licexpiration.rb
class Licexpiration < ActiveRecord::Base

	belongs_to :provider
	belongs_to :license

	accepts_nested_attributes_for :license
	
end

app/models/location.rb
class Location < ActiveRecord::Base
	belongs_to :provider
end

app/models/patient.rb
class Patient < ActiveRecord::Base

	belongs_to :user

	has_many :patientrelations
	has_many :providers, through: :patientrelations
	has_many :appointments

	has_attached_file :image, styles: { medium: "400x400#", small: "200x200#", thumb: "100x100" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

end

app/models/patientrelation.rb
class Patientrelation < ActiveRecord::Base

	belongs_to :provider
	belongs_to :patient
	belongs_to :patientrelationtype

	accepts_nested_attributes_for :patient
end

app/models/patientrelationtype.rb
class Patientrelationtype < ActiveRecord::Base

	has_many :patientrelations

end

app/models/provider.rb
class Provider < ActiveRecord::Base
	searchkick

	belongs_to :user
	belongs_to :specialty

	has_many :patientrelations
	has_many :patients, through: :patientrelations
	accepts_nested_attributes_for :patientrelations, reject_if: :all_blank, allow_destroy: true
	accepts_nested_attributes_for :patients, reject_if: :all_blank, allow_destroy: true

	has_many :locations
	accepts_nested_attributes_for :locations, reject_if: :all_blank, allow_destroy: true

	has_many :licexpirations
	has_many :licenses, through: :licexpirations
	accepts_nested_attributes_for :licexpirations, reject_if: :all_blank, allow_destroy: true
	accepts_nested_attributes_for :licenses, reject_if: :all_blank, allow_destroy: true

	has_many :appointments

	validates :name, :specialty, :image, presence: true
	has_attached_file :image, styles: { medium: "400x400#", small: "200x200#", thumb: "100x100" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/specialty.rb
class Specialty < ActiveRecord::Base

	has_many :providers

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :usertype

  has_many :providers
  has_many :patients
end

app/models/usertype.rb
class Usertype < ActiveRecord::Base
	has_many :users
end

app/controllers/patientrelations_controller.rb
class PatientrelationsController < ApplicationController

	before_action :find_patientrelation, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show]

	def index
		@patientrelation = Patientrelation.all.order("created_at DESC")
	end

	def show
	end

	def new
		@patientrelation = Patientrelation.new
	end

	def create
		@patientrelation = Patientrelation.new(patientrelation_params)

		if @patientrelation.save
			redirect_to @patientrelation, notice: "Successfully created relationship"
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @patientrelation.update(patientrelation_params)
			redirect_to @patientrelation
		else
			render 'edit'
		end
	end

	def destroy
		@patientrelation.destroy
		redirect_to root_path, notice: "Successfully deleted relationship"
	end

	private

		def patientrelation_params
			params.require(:patientrelation). permit(:patient_id, :provider_id, :patientrelationtypes_id, provider_attributes:[:id, :name], patient_attributes:[:id, :first_name, :last_name])
		end

		def find_patientrelation
			@patientrelation = Patientrelation.find(params[:id])
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/defineuser_helper.rb
module DefineuserHelper
end

app/helpers/licenses_helper.rb
module LicensesHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/patientrelations_helper.rb
module PatientrelationsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/patientrelations/_form.html.haml
= simple_form_for @patientrelation, HTML: { multipart: true } do |f|
	- if @patientrelation.errors.any?
		#errors
			%p
				= @patientrelation.errors.count
				Prevented this relationship from saving
			%ul
				- @patientrelation.errors.full_messages.each do |msg|
					%li = msg
	.panel-body
		= f.input :patientrelationtypes_id, input_html: {class: 'form-control'}
		= f.input :provider_id, input_html: {class: 'form-control'}
		= f.input :patient_id, input_html: {class: 'form-control'}

	= f.button :submit, class: "btn btn-primary"

app/views/patientrelations/edit.html.haml
%h1 Edit Provider

= render 'form'

app/views/patientrelations/index.html.haml
%tbody
	- @articles.each do |article|
		%tr
			%td= article.first_name
			%td= article.last_name
			%td= link_to 'Show', "providers/show"
			%td= link_to 'Edit', "providers/edit"

app/views/patientrelations/new.html.haml
%h1 New Patient Relation

= render 'form'

%br/

= link_to "Back", root_path, class: "btn btn-default"

app/views/patientrelations/show.html.haml
.main-content
	#provider_top.row
		.col-md-4
			HOLD
		.col-md-8
			#provider_info
				%p.description= @patientrelation.patientrelationtypes_id
				%p.description= @patientrelation.provider.name	
				%p.description= @patientrelation.patient.last_name		
	

	.row
		.col-md-12
			= link_to "Back", root_path, class: "btn btn-default" 
			- if user_signed_in?
				= link_to "Edit", edit_patientrelation_path, class: "btn btn-default" 
				= link_to "Delete", patientrelation_path, method: :delete, data: { confirm: "Are you sure about that mofo?" }, class: "btn btn-default"	
				= link_to "Request Appointment", new_appointment_path, class: "btn btn-default" 